name: z-wechat-bot

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download z-wechat-bot.zip
        run: |
          wget -O 'z-wechat-bot.zip' 'https://file.zzzwb.nyc.mn/z-wechat-bot.zip'

      - name: Unzip the downloaded file
        run: |
          unzip z-wechat-bot.zip

      - name: Remove the zip file
        run: |
          rm -f z-wechat-bot.zip

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes to the repository
        run: |
          git add .
          git commit -m "Update files"
          git push origin $(git rev-parse --abbrev-ref HEAD)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
